### PR TITLE
added option as 4th parameter to resolvers

### PR DESCRIPTION
**Pull request by jdesmarais1**

### CODE REVIEW

**Comment by jakelacey2012** [comment]
@jdesmarais1 you're more likely to get this merged in if you give a description with what you have changed also linking to the issue :)

**Comment by thebigredgeek** [comment]
https://github.com/thebigredgeek/apollo-resolvers/issues/19

**Comment by thebigredgeek** [comment]
bump

**Comment by arist0tl3** [comment]
@thebigredgeek 

Just curious what you're thinking for test coverage. A quick glance looks like updating `/unit/resolver_spec.js` with the additional param makes sense? Not sure what else you'd want to see tested, as this seems to just be a passthrough for the 4th param?

My only suggestion would be to change the name from `options` to `info`, to reflect the spec a bit more closely.

Happy to submit an update to the docs also.

**Comment by Corjen** [comment]
Implementing this would be great! Renaming from `options` to `info` is better indeed. 

The 4th param is just a passthrough that is used by [prisma](https://www.prisma.io/) and probably other tools as well. Any change this can get implemented? What changes would you like to see in the docs? Happy to help out!

**Comment by thebigredgeek** [comment]
Add an extra test case.  I'd rather be safer than sorry haha

**Pull request closed without merging**
