### PR TITLE
[WIP]:Initial Compose functionality and tests

### PR DESCRIPTION
**Pull request by mringer**
#4 

Quick and dirty implementation of the compose functionality proposed in the API v2 thread.  
With some basic tests.

Proposed Usage: 
```JavaScript
// This works.
const base = new Composable( resolve => {}, error => {} );
const composed = base.compose( { 
  r1: { resolve: r => {}, error: e =>  }, 
  r2: { resolve: r => {}, error: e =>  },
  r3: resolve => {}
});

// probably need to bump up the ES version to make this work.
const gqlResolvers = { Mutaitons: { ...composed } };
```

### CODE REVIEW

**Comment by thebigredgeek** [comment]
Couldn't we just add a compose helper similar to `and` and `or`?

**Comment by mringer** [comment]
Yeah, absolutely. Figured I'd stick strictly to the proposed implementation in the v2 spec, but that's totally reasonable.

**Comment by thebigredgeek** [comment]
Oh I see what you did.  This is actually quite clever!  Let's stick with this approach

**Comment by mringer** [comment]
Yeah, we can make composable a function, rather than a class. It's more consistent with the rest of the API.

**Comment by thebigredgeek** [comment]
Right, sorry... what I meant was that couldn't we just do something like...

```js

const base = createResolver(
   () => undefined,
   err => err
);

// All composed will pass calls and bubble errors though base.
const composed = base.compose( { 
  r1: { resolve: r => {}, error: e => {}  },  // declate separate resolve and error handlers
  r3: resolve => {}, // resolve declared inline 
  r4: myResolver // reuse a pre-constructed resolver
});

// And provide your Query and Mutation wiring like so...

{ Query: {
  someResolver: resFn,
  ...composed
},
Mutation: {
  someMutation: muteFn,
  ...composed
}
```

**Comment by thebigredgeek** [comment]
@mringer bump

**Comment by mringer** [comment]
Word, busy couple weeks at work, should be able to circle back to this in the next couple days.

**Comment by mringer** [comment]
@thebigredgeek I think this is what you were asking for.

**Pull request merged**
